import { useEffect, useState } from 'react';
import { Card, Spinner } from '@/components/ui';
import { getOperationalIntelligence, type IntelligenceData } from '@/modules/intelligence/services/operationalIntelligence.service';

export function OperationalIntelligencePage(){
 const [data,setData]=useState<IntelligenceData|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{setData(await getOperationalIntelligence({}))}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar a inteligência operacional.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const scoreLabel=(score:number)=>score>=80?'Saudável':score>=60?'Atenção':'Crítico';
 return <div className="space-y-6"><div className="flex items-end justify-between gap-4"><div><h1 className="text-2xl font-bold">Inteligência Operacional</h1><p className="text-sm text-slate-500">SLA, produtividade e saúde da operação.</p></div><button onClick={load} disabled={loading} className="rounded-lg bg-slate-900 px-4 py-2 text-sm text-white disabled:opacity-50">Atualizar</button></div>{error&&<div className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}{loading?<div className="flex justify-center p-10"><Spinner/></div>:data&&<><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card><p className="text-sm text-slate-500">Saúde operacional</p><p className="text-3xl font-bold">{data.healthScore}</p><p className="text-xs text-slate-500">{scoreLabel(data.healthScore)}</p></Card><Card><p className="text-sm text-slate-500">Conclusão</p><p className="text-3xl font-bold">{data.completionRate}%</p><p className="text-xs text-slate-500">{data.completed} de {data.total}</p></Card><Card><p className="text-sm text-slate-500">Atividades atrasadas</p><p className="text-3xl font-bold">{data.overdue}</p></Card><Card><p className="text-sm text-slate-500">Prioridade crítica</p><p className="text-3xl font-bold">{data.critical}</p></Card></div><Card><h2 className="mb-4 font-semibold">Distribuição por prioridade</h2><div className="space-y-3">{data.byPriority.map(x=>{const max=Math.max(1,...data.byPriority.map(i=>i.total));return <div key={x.label}><div className="mb-1 flex justify-between text-sm"><span className="capitalize">{x.label}</span><span>{x.total}</span></div><div className="h-2 rounded bg-slate-100"><div className="h-2 rounded bg-slate-900" style={{width:`${Math.max(4,x.total/max*100)}%`}}/></div></div>})}</div></Card><Card><h2 className="font-semibold">Regras de gestão</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-slate-600"><li>Priorize atividades atrasadas e críticas.</li><li>Use o score para acompanhar a saúde geral da operação.</li><li>Revise a distribuição de prioridades para evitar concentração de urgências.</li></ul></Card></>}</div>
}
