import { useEffect, useState, type ReactNode } from 'react';
import { supabase } from '@/lib/supabase';
import { Card, Spinner, Badge } from '@/components/ui';
import { getDashboardMetrics, type DashboardMetrics } from '@/modules/dashboard/services/dashboard.service';
import { PROJECT_STATUS_LABELS, PROJECT_STATUS_COLORS, ACTIVITY_STATUS_LABELS, ACTIVITY_STATUS_COLORS, type Project, type Activity } from '@/types';
import { HardHat, Activity as ActivityIcon, ClipboardList, CheckCircle2, Clock, MapPin, Wallet, Fuel, Wrench, RefreshCw, AlertTriangle } from 'lucide-react';

const money = (v:number) => new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v);
const initial:DashboardMetrics={projectsActive:0,activitiesInProgress:0,activitiesCompleted:0,activitiesPending:0,activitiesToday:0,workOrdersOpen:0,expensesMonth:0,fuelMonth:0,maintenanceMonth:0};

export function DashboardPage({ onOpenActivity }: { onOpenActivity?: (id: string) => void }) {
 const [loading,setLoading]=useState(true), [error,setError]=useState<string|null>(null), [metrics,setMetrics]=useState(initial);
 const [recentActivities,setRecentActivities]=useState<(Activity & {project:Project|null})[]>([]), [recentProjects,setRecentProjects]=useState<Project[]>([]);
 const load=async()=>{setLoading(true);setError(null);try{const [m,a,p]=await Promise.all([getDashboardMetrics(),supabase.from('activities').select('*, project:projects(*)').order('created_at',{ascending:false}).limit(6),supabase.from('projects').select('*').order('created_at',{ascending:false}).limit(6)]);if(a.error)throw a.error;if(p.error)throw p.error;setMetrics(m);setRecentActivities((a.data??[]) as (Activity & {project:Project|null})[]);setRecentProjects((p.data??[]) as Project[])}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar o dashboard.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 if(loading)return <Spinner/>;
 const cards=[['Obras ativas',metrics.projectsActive,<HardHat size={20}/>, 'text-blue-600 bg-blue-50'],['Em andamento',metrics.activitiesInProgress,<ActivityIcon size={20}/>, 'text-amber-600 bg-amber-50'],['Concluídas',metrics.activitiesCompleted,<CheckCircle2 size={20}/>, 'text-emerald-600 bg-emerald-50'],['Planejadas',metrics.activitiesPending,<Clock size={20}/>, 'text-slate-600 bg-slate-100'],['Atividades hoje',metrics.activitiesToday,<ClipboardList size={20}/>, 'text-indigo-600 bg-indigo-50']] as [string, number, ReactNode, string][];
 const total=metrics.activitiesCompleted+metrics.activitiesInProgress+metrics.activitiesPending; const pct=(n:number)=>total?Math.round(n*100/total):0;
 return <div className="page-container">
  <div className="flex items-start justify-between gap-4"><div><h1 className="text-2xl font-bold text-slate-900 dark:text-white">Dashboard executivo</h1><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Visão consolidada das operações, custos e produtividade</p></div><button onClick={load} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm hover:bg-slate-50"><RefreshCw size={16}/>Atualizar</button></div>
  {error&&<Card className="border-red-200"><div className="flex items-center gap-2 text-sm text-red-600"><AlertTriangle size={18}/>{error}</div></Card>}
  <div className="card-grid">{cards.map(([label,value,icon,color])=><Card key={label} className="metric-card"><div className={`mb-3 inline-flex h-10 w-10 items-center justify-center rounded-lg ${color}`}>{icon}</div><p className="text-2xl font-bold text-slate-900 dark:text-white">{value}</p><p className="mt-0.5 text-xs text-slate-500 dark:text-slate-400">{label}</p></Card>)}</div>
  <div className="grid gap-6 lg:grid-cols-3"><Card className="content-card lg:col-span-2"><h2 className="mb-5 text-base font-semibold">Operação</h2>{([['Concluídas',metrics.activitiesCompleted],['Em andamento',metrics.activitiesInProgress],['Planejadas',metrics.activitiesPending]] as [string, number][]).map(([l,v])=><div key={l} className="mb-4"><div className="mb-1 flex justify-between text-sm"><span>{l}</span><span className="font-medium">{v} ({pct(v)}%)</span></div><div className="h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-slate-700" style={{width:`${pct(v)}%`}}/></div></div>)}</Card>
   <Card className="content-card"><h2 className="mb-4 text-base font-semibold">Custos do mês</h2><div className="space-y-4"><div className="flex items-center gap-3"><Wallet size={18}/><div><p className="text-xs text-slate-500">Despesas</p><p className="font-semibold">{money(metrics.expensesMonth)}</p></div></div><div className="flex items-center gap-3"><Fuel size={18}/><div><p className="text-xs text-slate-500">Combustível</p><p className="font-semibold">{money(metrics.fuelMonth)}</p></div></div><div className="flex items-center gap-3"><Wrench size={18}/><div><p className="text-xs text-slate-500">Manutenção</p><p className="font-semibold">{money(metrics.maintenanceMonth)}</p></div></div><div className="border-t pt-3 font-bold">Total: {money(metrics.expensesMonth+metrics.fuelMonth+metrics.maintenanceMonth)}</div></div></Card></div>
  <div className="grid min-w-0 gap-6 lg:grid-cols-2"><Card className="content-card"><h2 className="mb-4 text-base font-semibold">Atividades recentes</h2>{recentActivities.length===0?<p className="py-8 text-center text-sm text-slate-400">Nenhuma atividade registrada</p>:<div className="space-y-3">{recentActivities.map(act=><button key={act.id} onClick={()=>onOpenActivity?.(act.id)} className="flex w-full items-center justify-between rounded-lg border border-slate-100 p-3 text-left hover:bg-slate-50"><div className="min-w-0"><p className="truncate text-sm font-medium">{act.title}</p><p className="truncate text-xs text-slate-400">{act.project?.name??'-'}</p></div><Badge className={ACTIVITY_STATUS_COLORS[act.status]}>{ACTIVITY_STATUS_LABELS[act.status]}</Badge></button>)}</div>}</Card>
  <Card className="content-card"><h2 className="mb-4 text-base font-semibold">Obras recentes</h2>{recentProjects.length===0?<p className="py-8 text-center text-sm text-slate-400">Nenhuma obra cadastrada</p>:<div className="space-y-3">{recentProjects.map(proj=><div key={proj.id} className="flex items-center justify-between rounded-lg border border-slate-100 p-3"><div className="min-w-0"><p className="truncate text-sm font-medium">{proj.code} - {proj.name}</p><p className="flex items-center gap-1 truncate text-xs text-slate-400"><MapPin size={12}/>{proj.city??'-'}, {proj.state??'-'}</p></div><Badge className={PROJECT_STATUS_COLORS[proj.status]}>{PROJECT_STATUS_LABELS[proj.status]}</Badge></div>)}</div>}</Card></div>
 </div>
}
