import { useEffect,useState } from 'react';
import { Card, Spinner, Badge } from '@/components/ui';
import { listExpenses, updateExpenseStatus, type Expense, type ExpenseStatus } from '@/modules/expenses/services/expenses.service';
import { formatCurrency, formatDate } from '@/lib/utils';
import { canManageFinancialData } from '@/shared/security/permissions'; import { useAuth } from '@/context/AuthContext';
const labels:Record<ExpenseStatus,string>={draft:'Rascunho',pending:'Pendente',under_review:'Em análise',approved:'Aprovada',rejected:'Rejeitada',paid:'Paga'};
export function ExpensesPage(){const {profile}=useAuth(); const [items,setItems]=useState<Expense[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState<string|null>(null);
const load=async()=>{setLoading(true);setError('');try{setItems(await listExpenses())}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar as despesas.')}finally{setLoading(false)}};useEffect(()=>{load()},[]);
const change=async(id:string,status:ExpenseStatus)=>{setBusy(id);try{await updateExpenseStatus(id,status);await load()}catch(e){setError(e instanceof Error?e.message:'Erro ao atualizar despesa.')}finally{setBusy(null)}};
return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Despesas e Prestação de Contas</h1><p className="text-sm text-slate-500">Acompanhe, analise e aprove despesas operacionais.</p></div>{error&&<div className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}<Card>{loading?<div className="flex justify-center p-10"><Spinner/></div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-slate-500"><th className="p-3">Data</th><th className="p-3">Categoria</th><th className="p-3">Descrição</th><th className="p-3">Valor</th><th className="p-3">Status</th><th className="p-3">Ação</th></tr></thead><tbody>{items.map(x=><tr key={x.id} className="border-b"><td className="p-3">{formatDate(x.expense_date)}</td><td className="p-3">{x.category}</td><td className="p-3">{x.description}</td><td className="p-3 font-semibold">{formatCurrency(x.amount)}</td><td className="p-3"><Badge>{labels[x.status]}</Badge></td><td className="p-3">{canManageFinancialData(profile?.role)&&['pending','under_review'].includes(x.status)&&<div className="flex gap-2"><button disabled={busy===x.id} onClick={()=>change(x.id,'approved')} className="rounded bg-emerald-600 px-2 py-1 text-xs text-white disabled:opacity-50">Aprovar</button><button disabled={busy===x.id} onClick={()=>change(x.id,'rejected')} className="rounded bg-rose-600 px-2 py-1 text-xs text-white disabled:opacity-50">Rejeitar</button></div>}</td></tr>)}</tbody></table>{items.length===0&&<div className="p-10 text-center text-slate-500">Nenhuma despesa encontrada.</div>}</div>}</Card></div>}
